[project]
name = "inari-tool"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.16",
]
